### sign up

@url_dev=http://localhost:3052/v1/api/

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    'name': 'Shop Shin',
    'email': 'shopshin@gmail.com',
    'password': 'abc123'
}